site_name: Prompter Docs
repo_url: https://github.com/odewahn/prompter
nav:
  - Home: index.md
  - Key Concepts: concepts.md
  - Installation: installation.md
  - Examples: examples.md
  - Command Reference: command-ref.md
  - API Reference: api-ref.md
theme:
  material
markdown_extensions:
  - pymdownx.blocks.admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
